package utils

var CATEGORY_KEYWORDS = map[string][]string{
	"dark_humor": {"dark joke", "morbid", "twisted humor", "offensive joke", "edgy joke"},
	"funny": {"lol", "hilarious", "lmao", "rofl", "comedy"},
	"sarcastic": {"oh sure", "totally", "yeah right", "as if", "obviously"},
	"satirical": {"political joke", "mock", "parody", "satire", "ridicule"},
	"witty": {"clever", "quick-witted", "sharp humor", "play on words", "smart joke"},
	"inspirational": {"believe", "achieve", "dream big", "never give up", "inspire"},
	"motivational": {"push forward", "stay strong", "you got this", "keep going", "work hard"},
	"philosophical": {"existence", "deep thought", "meaning of life", "what is real", "wisdom"},
	"whimsical": {"playful", "fanciful", "daydream", "quirky", "lighthearted"},
	"cynical": {"distrust", "skeptical", "pessimistic", "sarcastic", "bitter"},
	"romantic": {"love", "relationship", "heartfelt", "crush", "passionate"},
	"tragic": {"heartbreak", "lost", "devastated", "sorrow", "grief"},
	"nostalgic": {"childhood", "back in the day", "old times", "memory lane", "reminiscing"},
	"surreal": {"dreamlike", "unreal", "bizarre", "out of this world", "hallucination"},
	"absurd": {"ridiculous", "nonsense", "illogical", "crazy", "outrageous"},
	"paradoxical": {"contradiction", "mind-bending", "illogical", "conflicting", "mystifying"},
	"pun_based": {"wordplay", "double meaning", "play on words", "dad joke", "clever twist"},
	"irony_driven": {"unexpected", "opposite meaning", "ironic", "twist of fate", "contradiction"},
	"playful": {"fun-loving", "mischievous", "carefree", "cheeky", "lighthearted"},
	"edgy": {"provocative", "controversial", "shocking", "offensive", "daring"},
	"relatable": {"so me", "been there", "totally get it", "same here", "we've all been there"},
	"self_deprecating": {"I'm the worst", "I'm so dumb", "classic me", "fail", "self-roast"},
	"optimistic": {"glass half full", "hopeful", "bright future", "sunny outlook", "cheerful"},
	"pessimistic": {"doom", "nothing ever works", "pointless", "hopeless", "give up"},
	"quirky": {"odd", "unusual", "weird but fun", "peculiar", "eccentric"},
	"uplifting": {"cheer up", "stay positive", "happy vibes", "better days ahead", "joyful"},
	"thought_provoking": {"deep thought", "makes you think", "mind-expanding", "question everything", "introspective"},
	"deep_reflective": {"soul-searching", "philosophical", "profound", "existential", "meditative"},
	"clever_brainy": {"intelligent", "genius", "smart play", "brain teaser", "sharp-witted"},
	"controversial": {"hot take", "debate", "argument", "triggering", "polarizing"},
	"melancholic": {"blue", "downcast", "gloomy", "wistful", "heavy-hearted"},
	"energetic": {"hyped", "pumped", "full of energy", "high-energy", "excited"},
	"cultural_commentary": {"society", "modern world", "trends", "social norms", "cultural critique"},
	"fantasy_inspired": {"magic", "dragons", "mythical", "otherworldly", "enchanted"},
	"science_fictional": {"aliens", "future tech", "space travel", "dystopian", "cyberpunk"},
	"satirical_parody": {"mocking", "exaggeration", "spoof", "over-the-top", "ridicule"},
	"childlike": {"innocent", "wonder", "curious", "playful", "joyful"},
	"mature_humor": {"adult jokes", "innuendo", "subtle humor", "sophisticated", "grown-up comedy"},
	"random_spontaneous": {"out of nowhere", "unexpected", "spontaneous", "random thought", "completely unrelated"},
	"relationship": {"dating", "love life", "couple goals", "breakup", "romance"},
	"business": {"entrepreneur", "startup", "corporate", "finance", "industry"},
	"adventure": {"thrill-seeking", "journey", "exploration", "exciting", "travel"},
	"mystery": {"unknown", "whodunit", "puzzle", "detective", "clues"},
	"historical": {"past", "ancient", "history lesson", "old days", "historic event"},
	"dystopian": {"bleak future", "oppressive", "nightmarish", "totalitarian", "post-apocalyptic"},
	"utopian": {"perfect world", "ideal society", "harmony", "flawless", "paradise"},
	"spiritual": {"soul", "divine", "meditation", "faith", "transcendence"},
	"scientific": {"experiment", "theory", "research", "data", "scientific method"},
	"technological": {"AI", "innovation", "gadgets", "cyber", "robotics"},
	"artistic": {"creativity", "expression", "visual art", "aesthetic", "abstract"},
}
